URL_SERVICE = "https://1b89b26d-c64f-4991-b438-cfa842045164.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCT_KITS_PATH = "/api/v1/products/kits/"
